name: HW2

on:
  push:
    branches: [ master, main ]
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/workflows/test-template
      env:
        test-name: hw2
      
    - name: HW2 tests
      run: stack test hw2
      
